import "./globals.css";
import type { Metadata } from "next";
import { useRouter } from 'next/router';
import { DarkModeProvider } from '@/context/darkModeContext';
import { AuthProvider } from '@/context/authContext';
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";


export const metadata: Metadata = {
  title: "Ideatec - Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-br">
      <body>
        <AuthProvider>
          <DarkModeProvider>
            <Cabecalho />
            
            <div className="home">
              {children}
              <Rodape />
            </div>
          </DarkModeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
